In [3]:
import pandas as pd
import numpy as np

In [6]:
a = [1,2,3,4,5]
s = pd.Series(a) # Single column is series but multiple colums is data frames
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
d = {"Naman":31 , "Gajraj":12 , "Sundaram":31}
m = pd.Series(d)
m

Naman       31
Gajraj      12
Sundaram    31
dtype: int64

In [17]:
# So in series single data is formed and stored whereas in the data frames multiple data is stored 
info = {"Name":["Nishant Kumar","Prashant Kumar"],
        "Roll number":[12,32]}
data_frame = pd.DataFrame(info)
data_Series = pd.Series(info)
#data_Series
data_frame

             Name  Roll number
0   Nishant Kumar           12
1  Prashant Kumar           32

In [4]:
# Real World work :
# To load real world data
# Their functions :
Data_Frame = pd.read_csv("healthcare_dataset.csv")
Data_Frame

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [29]:
# Some inspection is always required before loading the data into the Machine 
Data_Frame.head() # Shows 1st 5 from top of the data
Data_Frame.tail() # Shows last 5 from last of the data
Data_Frame.sample() # Shows the data from the single row it always as a sample gives a random data 
Data_Frame.shape # shape is the attribute
Data_Frame.dtypes # dtypes is the attribute
Data_Frame.info()
Data_Frame.describe()
Data_Frame.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [32]:
df = Data_Frame[['Name','Age']]
df.head()
df.tail()

                    Name  Age
55495  eLIZABeTH jaCkSOn   42
55496         KYle pEREz   61
55497       HEATher WaNG   38
55498     JENniFER JOneS   43
55499       jAMES GARCiA   53

In [ ]:
Data_Frame.loc[[55400]] # loc is here for rows segregation
# Whereas if you want to make the rows data changed then we need to use loc
# Now to slice the data on the basis of the rows present in the Data frames
# For slicing their is no need of list in the loc
Data_Frame.loc[100:105][['Name','Age']]

               Name  Age
100   mARcUS ZAmorA   69
101     KaTiE hENry   70
102  wilLIAm morTON   21
103  KaTRina maRTin   47
104    HunTeR mckAy   85
105    dWAYnE DAViS   28

In [ ]:
# Another way to use the row through indexing is 
Data_Frame.iloc[0:5][['Name']] # Same thing we are doing here but the different thing here is 
# the use of indexing

            Name
0  Bobby JacksOn
1   LesLie TErRy
2    DaNnY sMitH
3   andrEw waTtS
4  adrIENNE bEll

In [52]:
# Boolean filter
df_age = Data_Frame[0:5]
df_age['Age']>30

0    False
1     True
2     True
3    False
4     True
Name: Age, dtype: bool

In [56]:
# Boolean filtering
Df = Data_Frame[10:20]
Df[Df['Age']>40][['Name','Age','Gender']]

                  Name  Age  Gender
10    mIchElLe daniELs   72    Male
12       connOR HANsEn   75  Female
13        rObeRt bAuer   68  Female
14        bROOkE brady   44  Female
15  MS. nAtalIE gAMble   46  Female
16       haley perkins   63  Female
19      dANIEL schmIdt   63    Male

In [13]:
# Use of Boolean indexing
df_Df = Data_Frame[1:100]
df_Df[((df_Df["Age"]<60) |(df_Df["Blood Type"]=="A+")) & (df_Df["Insurance Provider"]=="Medicare")][["Age","Blood Type","Insurance Provider"]]

    Age Blood Type Insurance Provider
1    62         A+           Medicare
3    28         O+           Medicare
6    21        AB-           Medicare
11   38         A-           Medicare
33   43        AB-           Medicare
35   25        AB+           Medicare
39   57         B-           Medicare
50   30        AB-           Medicare
64   58         A-           Medicare
65   27        AB-           Medicare
66   59         B+           Medicare
69   19         A+           Medicare
84   26         B-           Medicare
90   49         B+           Medicare

In [ ]:
# Filtering Methods
Data_Frame[Data_Frame["Insurance Provider"].isin(["Medicare","Blue Cross"])][1:100]
Data_Frame[Data_Frame["Insurance Provider"].str.contains("Blue Cross")][1:100]
# So to avoid the use of Logical notations we can also use the Filtering methods like above in Pandas

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
15,MS. nAtalIE gAMble,46,Female,AB-,Obesity,2023-01-01,Maria Dougherty,Cline-Williams,Blue Cross,12263.357425,465,Elective,2023-01-11,Aspirin,Inconclusive
18,LuKE BuRgEss,34,Female,A-,Hypertension,2021-03-04,Justin Moore Jr.,Houston PLC,Blue Cross,18843.023018,260,Elective,2021-03-14,Aspirin,Abnormal
20,tIMOTHY burNs,67,Female,A-,Asthma,2023-06-28,Krista Smith,Jones LLC,Blue Cross,42.514589,115,Elective,2023-07-02,Aspirin,Normal
26,cathy sMaLl,51,Female,O-,Asthma,2023-12-23,Wendy Glenn,"Brown, and Jones Weaver",Blue Cross,26786.529555,401,Elective,2024-01-19,Ibuprofen,Normal
34,NicOlE RodriGUEz,30,Female,AB+,Diabetes,2020-01-17,Lynn Young,Poole Inc,Blue Cross,8408.949354,285,Emergency,2020-02-10,Lipitor,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,BRyaN bOwERS,63,Female,O+,Asthma,2020-09-01,Peter Martinez,"Ruiz, Scott Mitchell and",Blue Cross,9894.809407,403,Emergency,2020-10-01,Ibuprofen,Inconclusive
525,NIColE mArTIN,75,Female,AB-,Cancer,2019-11-18,Christopher Spears,"and Rodriguez Gallegos Henry,",Blue Cross,29995.428564,433,Emergency,2019-12-11,Paracetamol,Abnormal
527,TOM BRoWN,27,Male,A+,Diabetes,2020-08-01,Tina Ray,"Turner Bradford and Allison,",Blue Cross,48965.175803,251,Emergency,2020-08-26,Aspirin,Abnormal
531,KayLA PeREZ,57,Male,AB+,Cancer,2023-05-15,Derek Dorsey,Rogers-Robles,Blue Cross,36287.385064,263,Elective,2023-05-19,Lipitor,Inconclusive
536,jAnEt ROBERTs DDS,34,Male,AB+,Asthma,2020-01-07,Scott Herring,Clay LLC,Blue Cross,41122.289137,440,Urgent,2020-01-12,Paracetamol,Normal

In [ ]:
# Cleaning Data 
# Most important concept 

# 1. isnull()
Sum_null_Value = Data_Frame.isnull().sum()
Sum_null_Value
# we got already a clean data here as no null value is present 

# 2. dropna()
# To clean the data we need to drop all the null values such that data would not contain any null value
# But this is not the right way because this will lead to the problem of all rows removal
# But to remove the value specifically of all the columns 
drop = Data_Frame.dropna(subset=["Insurance Provider"]) # It will drop all the null values present in the column mentioned
# To perforn the value filling in the data then we need to use the fillna

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [31]:
df = Data_Frame[0:100]
df['Age'].value_counts() # For particular age what is the count

Age
58    5
63    5
38    4
76    3
30    3
67    3
34    3
80    3
27    3
18    3
57    3
26    3
23    3
51    2
33    2
43    2
44    2
59    2
72    2
20    2
31    2
84    2
22    2
49    2
55    2
24    2
81    2
74    2
73    2
62    1
46    1
68    1
75    1
82    1
21    1
36    1
28    1
48    1
77    1
25    1
70    1
78    1
65    1
83    1
42    1
40    1
19    1
29    1
61    1
60    1
35    1
79    1
53    1
Name: count, dtype: int64

In [ ]:
# When we need to remove the duplicate
df = Data_Frame[0:10]
ans =df.duplicated(subset=['Insurance Provider']).sum()

np.int64(5)

In [39]:
# Renaming the columns name 
Data_Frame.rename(columns={"Insurance Provider":"Ins. prov."},inplace=True)
Data_Frame

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Ins. prov.,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal